name: Integration Tests

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: "125.0.6422.141"

      - name: Configure chromedriver
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Cache Flutter SDK
        id: cache-flutter-sdk
        uses: actions/cache@v4
        with:
          path: ~/source/flutter/
          key: ${{ runner.os }}-flutter-sdk

      - name: Install forked Flutter
        if: steps.cache-flutter-sdk.outputs.cache-hit != 'true'
        run: |
          set -eux
          mkdir -p ~/source/flutter/
          cd ~/source/flutter/
          git clone --single-branch --branch joeriddles/chromedriver-prefs-v2 https://github.com/joeriddles/flutter.git
          cd ./flutter
          git remote add upstream https://github.com/flutter/flutter.git
          git fetch --quiet upstream
          ./bin/flutter update-packages
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run integration tests
        run: |
          ./integration-test.sh
      
      - name: Save test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots
