name: Integration Tests

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 126
          install-chromedriver: true
      
      - name: Configure chromedriver
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Restore Flutter SDK cache
        id: restore-flutter-sdk-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/source/flutter/
          key: ${{ runner.os }}-flutter-sdk

      - name: Install forked Flutter
        if: steps.restore-flutter-sdk-cache.outputs.cache-hit != 'true'
        run: |
          set -eux
          mkdir -p ~/source/flutter/
          cd ~/source/flutter/
          git clone --single-branch --branch joeriddles/chromedriver-prefs-v2 https://github.com/joeriddles/flutter.git
          cd ./flutter
          git remote add upstream https://github.com/flutter/flutter.git
          git fetch --quiet upstream
          ./bin/flutter update-packages
          echo "$PWD/bin" >> $GITHUB_PATH
      
      - name: Save Flutter SDK cache
        id: save-flutter-sdk-cache
        uses: actions/cache/save@v4
        with:
          path: ~/source/flutter/
          key: ${{ steps.restore-flutter-sdk-cache.outputs.cache-primary-key }}

      - name: Run integration tests
        run: |
          ./integration-test.sh
      
      - name: Save test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots
