name: Integration Tests

permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 126
          install-chromedriver: true
      
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release

      - name: Install forked Flutter
        run: |
          set -eux
          mkdir -p ~/source/flutter/
          cd ~/source/flutter/
          git clone --single-branch --branch joeriddles/chromedriver-prefs-v2 https://github.com/joeriddles/flutter.git
          cd ./flutter
          git remote add upstream https://github.com/flutter/flutter.git
          git fetch --quiet upstream
          ./bin/flutter update-packages
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run integration tests
        run: |
          # export DISPLAY=:99
          # sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

          brew install --cask xquartz
          echo "/opt/X11/bin" >> $GITHUB_PATH

          ./integration-test.sh
      
      - name: Save test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots
